### ISSUE TITLE
this.route.params.id => this.$route.params.id

### ISSUE THREAD

**Issue by acfasj** [lavas-project/codelab#14]
创建页面的 "我们注意到在 <template> 和 <script> 中分别出现了  {{$route.params.id}} 和 this.route.params.id", `this.route.params.id` 应为 `this.$route.params.id`

**Comment by PengXing** [comment]
codelab 哪个文件呢？贴个链接？

**Comment by acfasj** [comment]
@PengXing 忘记贴了， [链接](https://lavas.baidu.com/codelab/get-started/new-page-and-link)

**Comment by PengXing** [comment]
我已经更新了 https://github.com/lavas-project/codelab/blob/master/get-started/new-page-and-link.md
