### ISSUE TITLE
反馈：middleware/02prepare.md

### ISSUE THREAD

**Issue by lin09** [lavas-project/codelab#9]
module.exports = {
    router: {
        ssr: true, // 首屏服务端渲染
        mode: 'history',
        base: '/',
        pageTransition: {
            type: 'fade',
            transitionClass: 'fade'
        }
    }
};

  router: { ssr: true} // 首屏服务端渲染。这是什么鬼？？？？？？
ssr 不是在配置 build 里的吗

**Comment by PengXing** [comment]
这里估计写错了，ssr: true 是在 build 里，我改了一下。
